-- MySQL Script generated by MySQL Workbench
-- Sat Mar 10 01:48:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id5024134_db_cadtreesa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id5024134_db_cadtreesa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id5024134_db_cadtreesa` DEFAULT CHARACTER SET utf8 ;
USE `id5024134_db_cadtreesa` ;

-- -----------------------------------------------------
-- Table `id5024134_db_cadtreesa`.`TIPOS_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id5024134_db_cadtreesa`.`TIPOS_USUARIOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id5024134_db_cadtreesa`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id5024134_db_cadtreesa`.`USUARIOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cod_matricula` VARCHAR(12) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `id_tipo` INT NOT NULL,
  PRIMARY KEY (`id`, `id_tipo`),
  UNIQUE INDEX `codMatricula_UNIQUE` (`cod_matricula` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_USUARIOS_PRIVILEGIOS_idx` (`id_tipo` ASC),
  CONSTRAINT `fk_USUARIOS_PRIVILEGIOS`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `id5024134_db_cadtreesa`.`TIPOS_USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id5024134_db_cadtreesa`.`ARVORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id5024134_db_cadtreesa`.`ARVORES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_comum` VARCHAR(45) NOT NULL,
  `especie` VARCHAR(45) NULL,
  `familia` VARCHAR(45) NULL,
  `cap` FLOAT NULL,
  `altura_total` INT NULL,
  `classe_copa` ENUM('ampla', 'mediana', 'curta') NULL,
  `sanidade` ENUM('boa', 'média', 'ruim') NULL,
  `crescimento` ENUM('lento', 'devagar', 'normal', 'rápido', 'muito rápido') NULL,
  `pos_sociologica` ENUM('emergente', 'superior', 'médio', 'inferior', 'isolada') NULL,
  `utilizacao` VARCHAR(255) NULL,
  `caracteristicas` TEXT(1500) NULL,
  `img_arvore` LONGBLOB NULL,
  `latitude` DECIMAL(20,15) NULL,
  `longitude` DECIMAL(20,15) NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `validado` TINYINT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_ARVORES_USUARIOS1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_ARVORES_USUARIOS1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `id5024134_db_cadtreesa`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `id5024134_db_cadtreesa` ;

-- -----------------------------------------------------
-- Placeholder table for view `id5024134_db_cadtreesa`.`VW_ARVORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id5024134_db_cadtreesa`.`VW_ARVORES` (`id` INT, `nome_comum` INT, `especie` INT, `familia` INT, `cap` INT, `altura_total` INT, `classe_copa` INT, `sanidade` INT, `crescimento` INT, `pos_sociologica` INT, `utilizacao` INT, `caracteristicas` INT, `data_registro` INT, `usuario_nome` INT, `usuario_descricao` INT, `img_arvore` INT, `latitude` INT, `longitude` INT);

-- -----------------------------------------------------
-- View `id5024134_db_cadtreesa`.`VW_ARVORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id5024134_db_cadtreesa`.`VW_ARVORES`;
USE `id5024134_db_cadtreesa`;
CREATE OR REPLACE VIEW `VW_ARVORES` AS
SELECT 
ARVORES.id,
ARVORES.nome_comum,
IFNULL(ARVORES.especie, 'não informado') AS especie,
IFNULL(ARVORES.familia, 'não informado') AS familia,
IFNULL(CONCAT(ARVORES.cap, " ", "metros"), 'não informado') AS cap,
IFNULL(CONCAT(ARVORES.altura_total, " ", "metros"), 'não informado') AS altura_total,
IFNULL(ARVORES.classe_copa, 'não informado') AS classe_copa,
IFNULL(ARVORES.sanidade, 'não informado') AS sanidade,
IFNULL(ARVORES.crescimento, 'não informado') AS crescimento,
IFNULL(ARVORES.pos_sociologica, 'não informado') AS pos_sociologica,
IFNULL(ARVORES.utilizacao, 'não informado') AS utilizacao,
IFNULL(ARVORES.caracteristicas, 'não informado') AS caracteristicas,
DATE_FORMAT(ARVORES.data_registro, '%d/%m/%Y às %Hhrs %mmin %sseg') data_registro,
USUARIOS.nome usuario_nome,
TIPOS_USUARIOS.descricao usuario_descricao,
ARVORES.img_arvore,
ARVORES.latitude,
ARVORES.longitude
FROM ARVORES, USUARIOS, TIPOS_USUARIOS
WHERE ARVORES.id_usuario = USUARIOS.id
AND USUARIOS.id_tipo = TIPOS_USUARIOS.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
